### ISSUE TITLE
Diving 미팅내용 정리  (2018年05月16日 19:30~)

### ISSUE THREAD

**Issue by kidodat** [kidodat/OkinawaLovers#10]
날짜 : 2018년05월16일 19시30분 
장소: 류칸

미팅내용

#### 홈페이지에서 가장 어필하고 싶은 부분 
가겨은 다른 곳에 비해 싸지만 서비스는 다른 곳에 뒤지지 않는다.
그 예로 
1. 스노쿨링 강습 진행시 한 팀당 한 명의 강사가 붙는 점
2. 다이빙 시에는 손님 2명당 한명의 강사가 따라 붙는 점

#### 메뉴 순서 변경 (이성민)
1. 다이빙소개 
2. 프로그램 소개
3. 흔적찾기
4. 미팅장소
5. 자주하는 질문
6. 예약문의

#### 모바일 디자인에 대해 (이성민)
모바일 디자인은 [마이다이빙]을 참조해서 디자인 할 것.

#### 예약란에 대해서 (박기도)

키:
120cm 에서 140cm 까지는 10cm 단위로 분류 
140cm 부터 220cm 까지는 5cm단위로 분류

체중:
20kg미안
20kg 에서 40kg까지는 5kg 단위
41부터 76까지는 3 단위로 
76-100
100부터 130까지는 10단위
131-150

신발 사이즈:
160-220은 10 단위
220-300은 5단위

도스마스크:
물속에서는 육지보다 약 1.3배 크게 보임으로
정말 눈이 나쁘신(0.5이하) 분만 착용할 것.
도스마스크 설명에 관해서는 핑크머메이드사이트를 참고할 것.

예약입력란에서 주소란을 없애기.

최대 인원수 다섯명으로 하고
6명이상은 단체로

예약 메일 (박기도)
땡큐페이지를 만들어서 표시.
예약을 하면 신청확인 메일과 예약확정 메일 즉 2통이 전달된 다는 것을 분명히 할 것.

예약란에서 동의 하는 곳에 글이 너무 많음.

건강체크는 너무 자세하게 쓰지 않기로 하기.

#### 미팅장소 (박기도)

구글 맵에서 경유지 설정하게 하기.
현재 경유지가 2곳 설정되어 있는데 한 곳 더 추가하기.

구글맵에서 주차장 추가할 것. 

주차장을 무료로 하고 메인페이지에 이  사실을 게시 할 것.

#### 흔적란(이성민)
글을 3개만 표시 하기

#### 팝업()
바베큐 자료를 올릴 것.

#### footer
마이다이비을 참조 할 것.

#### 광고 계약건
연관 검색어 2개를 계약함.
키워드1 오키나와 다이빙
키워드2 오키나와 스노켈링
가격은 한 개당 만오천엔

**Comment by harupa** [comment]
땡큐 ㅋ 이번주말에 할일 담당정하고 일정 짜보자! 파이팅~
