### ISSUE TITLE
장부

### ISSUE THREAD

**Issue by kidodat** [kidodat/OkinawaLovers#11]
### 지출

- [ ] 주차비(이토카즈씨와 원근이형네 사무실에서 미팅)
  * 가격: 600엔
  * 날짜 : 20180516
  * 지출자: 박기도

- [ ] 주차비(이토카즈씨와 원근이형네 사무실에서 미팅)
  * 가격: 600엔
  * 날짜 : 20180516
  * 지출자: 이성민

- [ ] 영호형 생일 케익
  * 가격: 1530엔
  * 날짜 : 20180520
  * 지출자: 박기도

- [ ] 형님들 담배
  * 가격: 470엔
  * 날짜 : 20180520
  * 지출자: 박기도

- [ ] 주차비(성민이형이랑 같이 스타트업 카페 갓는데 허탕침)
  * 가격: 100엔
  * 날짜 : 20180520
  * 지출자: 박기도

- [ ] 요구르트 2개 (서핑샵에서 블로그 사진찰영을 위해서 구입함. 영수증 못 받음)
  * 가격: 840엔
  * 날짜 : 20180520
  * 지출자: 박기도

- [ ] 주차비(스타트업 카페 1회 상담)
  * 가격: 250엔
  * 날짜 : 20180521
  * 지출자: 박기도

- [ ] 주차비(스타트업 카페 1회 상담)
  * 가격: 200엔
  * 날짜 : 20180521
  * 지출자: 이성민

- [ ] Elementor Pro for 1 Year
  * 가격: ＄99
  * 날짜 : 20180521
  * 지출자: 이성민

- [ ] 다이빙20 연관 검색어 2건
  * 가격: 30만원
  * 입금은행: 기업은행  
  * 계좌번호: 239-077925-01-013
  * 날짜 : 20180522
  * 입금자명: 박주환
  * 지출자 : 이성민

- [ ] 닷홈 웹호스팅 2계정(1년짜리)
  * 가격: 71,500원 * 2 = 143,000원
  * 날짜 : 20180522
  * 지출자: 이성민

- [ ] 점심값(서핑샵(아일랜드 브레이크) 근처 타코라이스가게)
  * 가격: 1500엔
  * 날짜 : 20180526
  * 지출자: 박기도

- [ ] 웹서버 1년치 (siteground)
  * 가격: USD $ 71.40
  * 날짜 : 20180605
  * 지출자: 이성민

- [ ] 도메인구입 2개
  * 가격: $17.43 X 2  =  $14.86
  * 날짜 : 20180605
  * 지출자: 이성민
>ryukyu-bnm.com
ok-okinawa.com

- [ ] 스카이프 전화번호 (050-5806-5928)
  * 가격: 2400円
  * 날짜 : 20180630
  * 지출자: 박기도

- [ ] 명함 https://www.vistaprint.jp/)
  * 가격: ¥3,628 x2 = 7,256
  * 날짜 : 20180701
  * 지출자: 박기도

- [ ] 장판 테이프
  * 가격: ¥2040 
  * 날짜 : 20180707
  * 지출자: 박기도

- [ ] 도장
  * 가격: ￥ 2,630  
  * 날짜 : 20180710
  * 지출자: 박기도

- [ ] 페인트 등 인테리어 물품
  * 가격: ￥ 7,377
  * 날짜 : 20180715
  * 지출자: 박기도

- [ ] 블라인드
  * 가격: ￥26,676円
  * 날짜 : 20180720
 `* 구입한 곳 :http://www.bicklycarpet.com/
  * 지출자: 박기도

- [ ] 화이트보드 시트
  * 가격: ￥ 2000円
  * 날짜 : 20180720
 `* 구입한 곳 :아마존
  * 지출자: 박기도

- [ ] 목재
  * 가격: ￥ 7365円
  * 날짜 : 20180721
 `* 구입한 곳 :아마존
  * 지출자: 박기도

- [ ] 약관공증
  * 가격: ￥ 5,2700円
  * 날짜 : 201803
 `* 구입한 곳 : 공증하는 곳
  * 지출자: 박기도

- [ ] 등기비
  * 가격: ￥ 75,000円
  * 날짜 : 20180807
  * 구입한 곳 :나하 법무국
  * 지출자: 박기도

- [ ] 종합여행시험비
  * 가격: ￥ 6,500円
  * 날짜 : 20180807
  * 구입한 곳 :우체국
  * 지출자: 박기도

- [ ] 종합여행 책(スラスラ覚える 国内・総合旅行業務取扱管理者 一挙合格ゼミ 改訂七版 )
  * 가격: ￥ 2,700 円
  * 날짜 : 20180728
  * 구입한 곳 :아마존
  * 지출자: 박기도

- [ ] 종합여행 책(やさしく学ぶ 総合旅行業務取扱管理者 改訂2版: -合格テキスト&練習問題-  )
  * 가격: ￥  1,290  円
  * 날짜 : 20180728
  * 구입한 곳 :아마존
  * 지출자: 박기도

- [ ] 사무실공사(천장, 외벽, 문)
  * 가격: ￥  73970円
  * 날짜 : 
  * 구입한 곳 :요시노 삼촌
  * 지출자: 박기도

**Comment by kidodat** [comment]
### 수익

- [ ] 다이빙20 연관 검색어 2건(오키나와 다이빙, 오키나와 스노쿨링) 3개월치
  * 가격: 90,000엔

- [ ] 아일랜드 브레이크 홈페이지 제작
  * 가격: 39,000엔

**Comment by harupa** [comment]
Elementor Pro for 1 Year
USD　＄99

**Comment by harupa** [comment]
지출
닷홈 웹호스팅 2계정(1년짜리)
71,500원 * 2  = 143,000원

**Comment by harupa** [comment]
지출
 SiteGround for 1 year
-  USD $ 71.40

Domains
-USD $17.43 X 2 domain
>ryukyu-bnm.com
>ok-okinawa.com
