### ISSUE TITLE
계정관리

### ISSUE THREAD

**Issue by harupa** [kidodat/OkinawaLovers#13]
엘리멘털 프로(3계정)
계정 : covocovo@naver.com
비번 : Leesm0828

**Comment by harupa** [comment]
닷홈 계정1(다이빙20용)-1년계약

[닷홈]
ryukyubnm
okinawa123

[ftp서버]
ryukyu1
ryukyu123

[db]
ryukyu1
ryukyu123

[WP]
admin
okinawa (임시)

**Comment by harupa** [comment]
닷홈 계정2(surfokinawa)-1년계약

[닷홈]
ryukyubnm
okinawa123

[ftp서버]
ryukyu2
ryukyu123

[db]
ryukyu2
ryukyu123

[WP]
admin
okinawa  (임시)

**Comment by harupa** [comment]
siteGround

haitai.love.okinawa@gmail.com
okinawa123

**Comment by kidodat** [comment]
109.199.126.141

**Comment by kidodat** [comment]
구글 
아이디 : ryukyubnm@gmail.com
비번 : !okinawa123

**Comment by harupa** [comment]
diving20.co.kr 
FTP 비번 !okinawa123

**Comment by harupa** [comment]
한국 도메인
hosting.kr
ryukyubnm
okinawa!12
