### ISSUE TITLE
OK-Okinawa컨셉

### ISSUE THREAD

**Issue by kidodat** [kidodat/OkinawaLovers#18]
### 컨셉
* 아이동반 가족
* 커플
* 대학생
* 아주머니

**Comment by kidodat** [comment]
필요한 플로그인 

- 예약관련
  1. https://woocommerce.com/products/woobookings-bundle/
- 결제 
  1. spike : 決済手数料は業界最安値の2.55%〜 + 10円〜でご利用いただけます
  2. stripe : 3.6%

괜찮은 테마
  1. https://demo.themovation.com/embark/#demos

**Comment by harupa** [comment]
메인슬라이더
렌트카(렌트시 예약대행)/숙박/액티비티1/액티비티2/액티비티3/액티비티4

메뉴구성
(렌트카+숙박)
렌트카
숙박
액티비티
관광지정보
고객센터
포켓와이파이/할인권
로그인
/날씨
/환율
/항공권 최저가검색
/구글맵/맵코드
/도와주세요

(
<해양스포츠>
다이빙/스노쿨링
서핑/윈드서핑
젯트스키/바나나보트
돌고래체험

<당일투어>
섬투어
버스투어

<필드>
패러글라이딩
골프
트랙킹
폭포트랙킹
카약
승마
도자기공방/시샤만들기
유리공방(류큐그라스)
자전거라이딩
)
관광정보(쇼핑/맛집/관광지/
