### ISSUE TITLE
[다이빙20] 견적서

### ISSUE THREAD

**Issue by kidodat** [kidodat/OkinawaLovers#2]
일단 초기비용은 (우리일당 * 일수(최대2주))해서  5만엔 ＋ 기능（플로그인 비용 등등）

**Comment by harupa** [comment]
요구1. 화면 보기 좋게 * 모바일에서 페이지 전체가 바로 눈에 들어오게.
요구2. 예약은 간편하게. * booking 으로 디자인 입혀서 한 페이지에서 끝내게. 항목은 추가 필수

**Comment by harupa** [comment]
프로젝트 수주하는데 의미를 두고 개발비용엔 연연하지 않을것.
네이버 연관검색에 지원 대응 - 견적금액에 최대 50%까지 수수료 생각하지만. 현실적인것은 고려할점.

**Comment by harupa** [comment]
sample page
haitailoveokinawa.000webhostapp.com
모바일 사이즈 대응 90% 정도. 
2018/4/28 오후에 첫 미팅.

**Comment by kidodat** [comment]
이번건 성사되면 원근이형에게 
저희 수입에 이십프로 정도 리베이트 형식으로 
드릴 것 한번 생각해 보는 것도 좋을 것 같아요.

**Comment by kidodat** [comment]
형 친구가 견적서 보내줬는데 생각보다 너무 비싸네요

키워드 | pc 조회수 | 모바일 조회수 | 블로그 월보장 | 모바일 보장 추가시 | 자동완성 | 연관검색어
-- | -- | -- | -- | -- | -- | --
오키나와 푸른동굴 | 1240 | 2350 | 600000 | 200000 | 150000 | 150000
오키나와 스노쿨링 | 2560 | 5980 | 500000 | 200000 | 150000 | 200000
오키나와스쿠버다이빙 | 910 | 1720 | 400000 | 150000 | 150000 | 150000
오키나와다이빙 | 830 | 1240 | 600000 | 200000 | 150000 | 150000
오키나와푸른동굴스노쿨링 | 1190 | 2800 | 400000 | 200000 | 150000 | 150000
오키나와 스킨스쿠버 | 330 | 660 | 300000 | 150000 | 150000 | 150000

**Comment by harupa** [comment]
다이빙20 업체 자료 방금 정리해서 
엑셀로 만들었당ㅋ 한번 참고용으로 봐바 ㅋ 급하게 만든거라 영 신통치않지만
https://drive.google.com/open?id=1DwxB6QYcrrcDU26SRWymB-9WTye5h9JS

**Comment by harupa** [comment]
다이빙20 업체에서 받음

홈페이지 요구명세서(제안서)
https://drive.google.com/open?id=1IA3RAB8aJBuXsrsdXfv47SMJ2Q4MLibr

**Comment by harupa** [comment]
이토카즈 컨펌중.
http://www.mydiving.info/kr/ 를 모델로 홈페이지 고퀄리티 요구 있음
메뉴구성 화면구성 등 모든 디자인 참고
레이아웃은 일단 모델을 참고로 제작시작. 
http://framebox.org/AFsqz 샘플 레이아웃
