### ISSUE TITLE
네이버 홍보 관련 자료 및 견적서

### ISSUE THREAD

**Issue by kidodat** [kidodat/OkinawaLovers#3]
### 네이버 홍보 건
* 회사명 
    * 에드리안-http://www.adrian.co.kr/  (주환이네 친구네 회사, 현재 주환이는 이 회사 직원)
* 홍보 방법
  * 네이버 연관 검색어에 원하는 키워드가 나오게함.
* 가격
  * 연관검색어
    * 한 건당 5만원, 10만원당 연관검색어 3-4건 등록가능
  * 자동완성
    * 건당 10만원 이상

**Comment by harupa** [comment]
10만원당 연관검색어 3-4건 등록가능

**Comment by kidodat** [comment]
### 블로그 홍보 건
* 회사명 
    * 아직 모름  (영범이네 친구네 회사)
* 홍보 방법
  * 관련 키워드가 검색 될 경우 블로그 카테고리에서 1-5번째 사이에 나오게 됨
* 가격
  * 30만원 (너무 비싼 것 같아서 도매가격으로 한번 흥정해 보려고 함. )

**Comment by harupa** [comment]
다이빙샵 오너로부터 홍보관련 구체적인 정보 요청 있음.
비용, 절차, 기대효과 <- 이건 나의(성민) 예상임
등의 홍보자료나 좀더 홍보를 고객한테 설명할수 있을 정도의 정보가 필요할듯.
추신) 한건당 5만원 이게 최신 정보야?

**Comment by kidodat** [comment]
영업해준 사람에게 리베이트 형식으로 지불할 것에 대해서 생각해 보기.

**Comment by kidodat** [comment]
현재 블로그 관련 정보 정리.

* 홍보자료
  * 한국어 홍보자료는 pdf형식으로 받았지만,  프레젠테이션 자료는 아직 못 받았음. 받으면 일본어로 번역해서 손님에게 제출 할 수 있도록 준비해야됨.
* 가격
  * 연관검색어는 오만원이 가장 저렴함.
  * 블로그 건은 키워드별로 가격이 다름
    * 키워드: 오키나와 다이빙, 가격: 30만원
    * 키워드: 오키나와 스노쿨링, 가격: 견적확인 중

**Comment by harupa** [comment]
다이빙샵 오너가 급한가 봄.
최대한 빨리 알고싶어하는데 이번주중에 가능한가?.. 검색어 등록 금액이 어느정도인지 
검색어별 인기등급이 있을거 같은데 ..  검색어 노출 + 클릭수로 비용 발생하는 그런것도 있는거 같던데
아무쪼록..  연락오면 연계부탁해

**Comment by kidodat** [comment]
형 회사 마치고 연락 드릴게요
