### ISSUE TITLE
샘플 웹페이지 

### ISSUE THREAD

**Issue by harupa** [kidodat/OkinawaLovers#6]
2018/4/27
https://drive.google.com/open?id=1Swf3e6-kPGjW3Wos-lsMFDjb5thZ-RJY
원근형님 미팅용  Import 용

plugin : All-in-One Wp Magraiton

**Comment by harupa** [comment]
신규 웹 사이트 링크 
https://mytestpage20.000webhostapp.com

아래는 초기화해서 사라짐
웹 사이트 링크 
http://haitailoveokinawa.000webhostapp.com/

**Comment by kidodat** [comment]
### 주요 FNQ　페이지 레이아웃 샘플

![fnq](https://user-images.githubusercontent.com/18319520/39482112-bb8d8920-4da8-11e8-99f4-fa71eba30d82.png)

저장이 안되서 업로드는 못했는데 이런 식으로 만들었어요.

* 추가 하고 싶은 기능:
  * 문의 메일을 바로 작성가능하도록 질문란을 하단 부에 표시할 것
* 참고사이트 : http://www.waikikimarinesports.com/?page_id=1867
