### ISSUE TITLE
20180509미팅 내용 정리 

### ISSUE THREAD

**Issue by kidodat** [kidodat/OkinawaLovers#8]
### 메인페이지 
![diving20](https://user-images.githubusercontent.com/18319520/39822789-676642b2-53e6-11e8-93ba-d6070f5b0bf7.png)

### 프로그램
![diving20](https://user-images.githubusercontent.com/18319520/39823178-6a7fc3e6-53e7-11e8-8cc4-c348744a8364.png)

### 미팅장소
![diving20](https://user-images.githubusercontent.com/18319520/39823446-0ba3d974-53e8-11e8-98cf-f6132158f62c.png)

### 예약문의 
![diving20](https://user-images.githubusercontent.com/18319520/39823690-883c9692-53e8-11e8-84b9-e09e196152fa.png)

### 그 밖의 사항

1. 자동송신 메일에 영어부분을 한글로 교체
2. 원근이형님이 예약 처리등을 수월하게 할 수 있도록 함.

**Comment by harupa** [comment]
5/14 홈페이지 제작용 사진입수. 확인은 아직.
